version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: um-nginx
    ports:
      - "8080:80"
    volumes:
      - ./Docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php

  php:
    container_name: um-php
    build: Docker
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    links:
      - mariadb
      
  composer_install:
    image: php:8.3.6-fpm
    container_name: composer-install
    volumes:
      - .:/var/www/html
    command: composer install -n
    depends_on:
      - php

  mariadb:
    image: mariadb:latest
    container_name: um-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usermanagement_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
